package com.example.chronos.ui.theme
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF8F4E00)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDCC2)
val md_theme_light_onPrimaryContainer = Color(0xFF2E1500)
val md_theme_light_secondary = Color(0xFF9C404A)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDADA)
val md_theme_light_onSecondaryContainer = Color(0xFF40000D)
val md_theme_light_tertiary = Color(0xFF7E5700)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDEAC)
val md_theme_light_onTertiaryContainer = Color(0xFF281900)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF251A00)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF251A00)
val md_theme_light_surfaceVariant = Color(0xFFF3DFD1)
val md_theme_light_onSurfaceVariant = Color(0xFF51443B)
val md_theme_light_outline = Color(0xFF847469)
val md_theme_light_inverseOnSurface = Color(0xFFFFEFD3)
val md_theme_light_inverseSurface = Color(0xFF3F2E00)
val md_theme_light_inversePrimary = Color(0xFFFFB77A)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF8F4E00)
val md_theme_light_outlineVariant = Color(0xFFD6C3B6)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFFB77A)
val md_theme_dark_onPrimary = Color(0xFF4C2700)
val md_theme_dark_primaryContainer = Color(0xFF6D3A00)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDCC2)
val md_theme_dark_secondary = Color(0xFFFFB2B6)
val md_theme_dark_onSecondary = Color(0xFF5F121F)
val md_theme_dark_secondaryContainer = Color(0xFF7D2933)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDADA)
val md_theme_dark_tertiary = Color(0xFFFBBB4A)
val md_theme_dark_onTertiary = Color(0xFF432C00)
val md_theme_dark_tertiaryContainer = Color(0xFF604100)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDEAC)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF251A00)
val md_theme_dark_onBackground = Color(0xFFFFDF9C)
val md_theme_dark_surface = Color(0xFF251A00)
val md_theme_dark_onSurface = Color(0xFFFFDF9C)
val md_theme_dark_surfaceVariant = Color(0xFF51443B)
val md_theme_dark_onSurfaceVariant = Color(0xFFD6C3B6)
val md_theme_dark_outline = Color(0xFF9E8E82)
val md_theme_dark_inverseOnSurface = Color(0xFF251A00)
val md_theme_dark_inverseSurface = Color(0xFFFFDF9C)
val md_theme_dark_inversePrimary = Color(0xFF8F4E00)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFB77A)
val md_theme_dark_outlineVariant = Color(0xFF51443B)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF100C09)
